generate-changelog: print an informative error message if the relevant milestone does not exist
Instead of:

  IndexError: list index out of range

It will now say:

  ValueError: Need exactly 1 milestone called 'Tails_6.8.2'

Which should help the RM figure out that they really have to go through the "In
the beginning of your shift" steps, because a few parts of our release process
assume these steps were performed.